application:
  name: gatsby-site-2
  project: gatsby2
  cloud_region: aws/us-west-2
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: gatsby-site-2
    paths:
    - /*
